Add screenshot url to the manifest
godaddy/wp-themes pull request #6
Opened 2017-03-09 16:35 UTC by EvanHerman

@fjarrett Please review.

I've gone ahead and updated the manifest to include the URL to the screenshots for use in the theme tab.

2017-03-09 17:00 UTC, fjarrett commented
@EvanHerman Did you already test to see if these changes break the [`Theme_Updates`](https://github.secureserver.net/WPPaaS/wp-paas-system-plugin/blob/8aeb64a29ab3787dd548a8b60df85933da242e37/gd-system-plugin/includes/class-theme-updates.php) class in the System Plugin?

2017-03-09 17:20 UTC, EvanHerman commented
@fjarrett I just tested and it works just fine when not on the VPN. Otherwise it times out.

2017-03-09 19:11 UTC, frankiejarrett requested changes
@EvanHerman Please add a unit test for `testScreenshotsReachable()` and an `assertStringEndsWith( 'screenshot.png' )` in the `testThemeData()` method.

2017-03-09 19:11 UTC, fjarrett commented on manifest.json
> +    "screenshot": "https://raw.githubusercontent.com/godaddy/wp-activation-theme/master/screenshot.png"
@EvanHerman The `screenshot` should reference the release tag, not `master`.

e.g. https://raw.githubusercontent.com/godaddy/wp-activation-theme/v1.1.1/screenshot.png

2017-03-10 06:17 UTC, frankiejarrett approved these changes

2017-03-10 06:17 UTC, merged